import uniqid from "uniqid";

export const todos = [
  {
    id: uniqid(),
    title: "delectus aut autem",
    completed: true,
    description: "test",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "quis ut nam facilis et officia qui",
    completed: false,
    description: "",
    priority: "medium",
  },
  {
    id: uniqid(),
    title: "fugiat veniam minus",
    completed: false,
    description: "",
    priority: "low",
  },
  {
    id: uniqid(),
    title: "et porro tempora",
    completed: true,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    completed: false,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "delectus aut autem",
    completed: true,
    description: "test",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "quis ut nam facilis et officia qui",
    completed: false,
    description: "",
    priority: "medium",
  },
  {
    id: uniqid(),
    title: "fugiat veniam minus",
    completed: false,
    description: "",
    priority: "low",
  },
  {
    id: uniqid(),
    title: "et porro tempora",
    completed: true,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    completed: false,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "delectus aut autem",
    completed: true,
    description: "test",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "quis ut nam facilis et officia qui",
    completed: false,
    description: "",
    priority: "medium",
  },
  {
    id: uniqid(),
    title: "fugiat veniam minus",
    completed: false,
    description: "",
    priority: "low",
  },
  {
    id: uniqid(),
    title: "et porro tempora",
    completed: true,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    completed: false,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "delectus aut autem",
    completed: true,
    description: "test",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "quis ut nam facilis et officia qui",
    completed: false,
    description: "",
    priority: "medium",
  },
  {
    id: uniqid(),
    title: "fugiat veniam minus",
    completed: false,
    description: "",
    priority: "low",
  },
  {
    id: uniqid(),
    title: "et porro tempora",
    completed: true,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    completed: false,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "delectus aut autem",
    completed: true,
    description: "test",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "quis ut nam facilis et officia qui",
    completed: false,
    description: "",
    priority: "medium",
  },
  {
    id: uniqid(),
    title: "fugiat veniam minus",
    completed: false,
    description: "",
    priority: "low",
  },
  {
    id: uniqid(),
    title: "et porro tempora",
    completed: true,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    completed: false,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "delectus aut autem",
    completed: true,
    description: "test",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "quis ut nam facilis et officia qui",
    completed: false,
    description: "",
    priority: "medium",
  },
  {
    id: uniqid(),
    title: "fugiat veniam minus",
    completed: false,
    description: "",
    priority: "low",
  },
  {
    id: uniqid(),
    title: "et porro tempora",
    completed: true,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    completed: false,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "delectus aut autem",
    completed: true,
    description: "test",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "quis ut nam facilis et officia qui",
    completed: false,
    description: "",
    priority: "medium",
  },
  {
    id: uniqid(),
    title: "fugiat veniam minus",
    completed: false,
    description: "",
    priority: "low",
  },
  {
    id: uniqid(),
    title: "et porro tempora",
    completed: true,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    completed: false,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "delectus aut autem",
    completed: true,
    description: "test",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "quis ut nam facilis et officia qui",
    completed: false,
    description: "",
    priority: "medium",
  },
  {
    id: uniqid(),
    title: "fugiat veniam minus",
    completed: false,
    description: "",
    priority: "low",
  },
  {
    id: uniqid(),
    title: "et porro tempora",
    completed: true,
    description: "",
    priority: "hight",
  },
  {
    id: uniqid(),
    title: "laboriosam mollitia et enim quasi adipisci quia provident illum",
    completed: false,
    description: "",
    priority: "hight",
  },
];
